using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using YamlDotNet.Core.Tokens;
using YamlDotNet.Serialization;

namespace KepwareSync.Model
{
    [Endpoint("/config/v1/project/channels/{name}")]
    public class Channel : BaseEntity
    {
        [YamlIgnore]
        public DeviceCollection? Devices { get; set; }
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}")]
    public class Device : DefaultEntity
    {
        [YamlIgnore]
        public DeviceTagCollection? Tags { get; set; }

        [YamlIgnore]
        public DeviceTagGroupCollection? TagGroups { get; set; }
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/tag_groups/{groupName}")]
    public class DeviceTagGroup : DefaultEntity
    {
        [YamlIgnore]
        public DeviceTagGroupTagCollection? Tags { get; set; }

        [YamlIgnore]
        public bool IsAutogenerated => GetDynamicProperty<bool>(Properties.NonSerialized.Autogenerated) == true;
    }

    [Endpoint("/config/v1/project/channels")]
    public class ChannelCollection : EntityCollection<Channel>
    {
        public ChannelCollection() {}

    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices")]
    public class DeviceCollection : EntityCollection<Device>
    {
        public DeviceCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/tags")]
    public class DeviceTagCollection : EntityCollection<DefaultEntity>
    {
        public DeviceTagCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/consumer_exchange_groups")]
    public class ConsumerExchangeGroupCollection : EntityCollection<DefaultEntity>
    {
        public ConsumerExchangeGroupCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/consumer_exchange_groups/{groupName}/consumer_exchanges")]
    public class ConsumerExchangeCollection : EntityCollection<DefaultEntity>
    {
        public ConsumerExchangeCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/producer_exchange_groups")]
    public class ProducerExchangeGroupCollection : EntityCollection<DefaultEntity>
    {
        public ProducerExchangeGroupCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/producer_exchange_groups/{groupName}/producer_exchanges")]
    public class ProducerExchangeCollection : EntityCollection<DefaultEntity>
    {
        public ProducerExchangeCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/omni_mapping_groups")]
    public class OmniMappingGroupCollection : EntityCollection<DefaultEntity>
    {
        public OmniMappingGroupCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/omni_mapping_groups/{groupName}/omni_mappings")]
    public class OmniMappingCollection : EntityCollection<DefaultEntity>
    {
        public OmniMappingCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/omni_mapping_groups/{groupName}/omni_mappings/{mappingName}/omni_gas_alarms")]
    public class OmniAlarmCollection : EntityCollection<DefaultEntity>
    {
        public OmniAlarmCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/tag_groups")]
    public class DeviceTagGroupCollection : EntityCollection<DeviceTagGroup>
    {
        public DeviceTagGroupCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/tag_groups/{groupName}/tags")]
    public class DeviceTagGroupTagCollection : EntityCollection<DefaultEntity>
    {
        public DeviceTagGroupTagCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/phonebooks")]
    public class PhonebookCollection : EntityCollection<DefaultEntity>
    {
        public PhonebookCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/phonebooks/{phonebookName}/phonelist")]
    public class PhoneEntryCollection : EntityCollection<DefaultEntity>
    {
        public PhoneEntryCollection() {}
    }

    [Endpoint("/config/v1/project/channels/{channelName}/devices/{deviceName}/device_profiles")]
    public class DeviceProfileCollection : EntityCollection<DefaultEntity>
    {
        public DeviceProfileCollection() {}
    }
}
