using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KepwareSync.Model
{
    public static class Properties
    {
        public const string DeviceDriver = "servermain.MULTIPLE_TYPES_DEVICE_DRIVER";
        public const string Description = "common.ALLTYPES_DESCRIPTION";
        public const string Name = "common.ALLTYPES_NAME";
        public const string ProjectId = "PROJECT_ID";

        public static class NonSerialized
        {
            public const string TagGrpTotalTagCount = "servermain.TAGGROUP_TOTAL_TAG_COUNT";
            public const string TagGrpTagCount = "servermain.TAGGROUP_LOCAL_TAG_COUNT";
            public const string ChannelTagCount = "servermain.CHANNEL_STATIC_TAG_COUNT";
            public const string Autogenerated = "servermain.TAGGROUP_AUTOGENERATED";
        }
    }
}
