using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using YamlDotNet.Serialization.NamingConventions;
using YamlDotNet.Serialization;
using KepwareSync.Model;
using KepwareSync.Serializer;
using YamlDotNet.Serialization.NodeTypeResolvers;
using System.Security.AccessControl;
using KepwareSync.Configuration;

namespace KepwareSync
{
    internal class KepFolderStorage
    {
        private readonly YamlSerializer m_yamlSerializer;
        private readonly CsvTagSerializer m_csvTagSerializer;
        private readonly DataTypeEnumConverterProvider m_dataTypeEnumConverterProvider;
        private readonly ILogger<KepFolderStorage> m_logger;
        private readonly KepStorageOptions m_kepStorageOptions;

        public KepFolderStorage(ILogger<KepFolderStorage> logger, KepStorageOptions kepStorageOptions)
        {
            m_logger = logger;
            m_kepStorageOptions = kepStorageOptions;
            m_yamlSerializer = new YamlSerializer();
            m_csvTagSerializer = new CsvTagSerializer();
            m_dataTypeEnumConverterProvider = new DataTypeEnumConverterProvider();
        }

        private void DeleteDirectories(string baseDir, IEnumerable<string> names)
        {
            // Delete all channel directories that are not in the current project   
            foreach (var dir in names)
            {
                var folderPath = Path.Combine(baseDir, dir);
                if (Directory.Exists(folderPath))
                {
                    Directory.Delete(folderPath, true);
                    m_logger.LogInformation($"Deleted folder: {folderPath}");
                }
            }
        }

        public async Task ExportChannelsAsYamlAsync(
            ChannelCollection? channels)
        {
            if (channels == null) return;

            DirectoryInfo baseDirInfo = new DirectoryInfo(m_kepStorageOptions.Directory ?? "ExportedYaml");

            if (!baseDirInfo.Exists)
                baseDirInfo.Create();

            var channelDirsToDelete = baseDirInfo.GetDirectories().Select(dir => dir.Name)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);

            List<(string baseDir, IEnumerable<string> folderNames)> foldersToDelete = [];

            foreach (var channel in channels)
            {
                var channelFolder = Path.Combine(baseDirInfo.FullName, channel.Name);
                channelDirsToDelete.Remove(channel.Name);

                // Export Channel
                var channelFile = Path.Combine(channelFolder, "channel.yaml");
                await m_yamlSerializer.SaveAsYaml(channelFile, channel);

                if (channel.Devices != null)
                {
                    var deviceDirsToDelete = new DirectoryInfo(channelFolder).GetDirectories().Select(dir => dir.Name)
                        .ToHashSet(StringComparer.OrdinalIgnoreCase);
                    foreach (var device in channel.Devices)
                    {
                        var deviceFolder = Path.Combine(channelFolder, device.Name);
                        var dataTypeConverter = m_dataTypeEnumConverterProvider.GetDataTypeEnumConverter(device.GetDynamicProperty<string>(Properties.DeviceDriver));
                        deviceDirsToDelete.Remove(device.Name);

                        // Export Device
                        var deviceFile = Path.Combine(deviceFolder, "device.yaml");
                        await m_yamlSerializer.SaveAsYaml(deviceFile, device);

                        if (device.Tags != null)
                            await m_csvTagSerializer.ExportTagsAsync(Path.Combine(deviceFolder, "tags.csv"), device.Tags.Items, dataTypeConverter);
                        // use CsvTagSerializer to export device.Tags as CSV 

                        if (device.TagGroups != null)
                        {
                            foreach (var tagGroup in device.TagGroups.Where(grp => !grp.IsAutogenerated))
                            {
                                var tagGroupFolder = Path.Combine(deviceFolder, tagGroup.Name);

                                // Export TagGroup
                                var tagGroupFile = Path.Combine(tagGroupFolder, "tagGroup.yaml");
                                await m_yamlSerializer.SaveAsYaml(tagGroupFile, tagGroup);

                                // use CsvTagSerializer to export tagGroup.Tags as CSV 
                                if (tagGroup.Tags != null)
                                    await m_csvTagSerializer.ExportTagsAsync(Path.Combine(tagGroupFolder, "tags.csv"), tagGroup.Tags.Items, dataTypeConverter);
                            }
                        }
                    }

                    foldersToDelete.Add((channelFolder, deviceDirsToDelete));
                }
            }

            DeleteDirectories(baseDirInfo.FullName, channelDirsToDelete);

            foreach (var (baseDir, folderNames) in foldersToDelete)
            {
                DeleteDirectories(baseDir, folderNames);
            }
        }
    }
}
