using Kepware.Api.Serializer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Threading.Tasks;

namespace Kepware.Api.Model
{
    /// <summary>
    /// Contains classes and definitions for API documentation.
    /// </summary>
    public static class Docs
    {
        /// <summary>
        /// Represents a driver in the API documentation.
        /// </summary>
        [Endpoint("/config/v1/doc/drivers/")]
        public class Driver
        {
            /// <summary>
            /// Gets or sets the namespace of the driver.
            /// </summary>
            [JsonPropertyName("namespace")]
            public string? Namespace { get; set; }

            /// <summary>
            /// Gets or sets the display name of the driver.
            /// </summary>
            [JsonPropertyName("display_name")]
            public string? DisplayName { get; set; }

            /// <summary>
            /// Gets or sets the documentation channels of the driver.
            /// </summary>
            [JsonPropertyName("doc_channels")]
            public string? DocChannels { get; set; }

            /// <summary>
            /// Gets or sets the documentation devices of the driver.
            /// </summary>
            [JsonPropertyName("doc_devices")]
            public string? DocDevices { get; set; }

            /// <summary>
            /// Gets or sets the documentation meter groups of the driver.
            /// </summary>
            [JsonPropertyName("doc_meter_groups")]
            public string? DocMeterGroups { get; set; }

            /// <summary>
            /// Gets or sets the documentation meters of the driver.
            /// </summary>
            [JsonPropertyName("doc_meters")]
            public string? DocMeters { get; set; }
        }

        /// <summary>
        /// Represents a collection definition in the API documentation.
        /// </summary>
        public abstract class CollectionDefinition
        {
            /// <summary>
            /// An empty collection definition.
            /// </summary>
            public static readonly CollectionDefinition Empty = new EmptyCollectionDefinition();

            /// <summary>
            /// Gets or sets the type definition of the collection.
            /// </summary>
            [JsonPropertyName("type_definition")]
            public TypeDefinition? TypeDefinition { get; set; }

            /// <summary>
            /// Gets or sets the property definitions of the collection.
            /// </summary>
            [JsonPropertyName("property_definitions")]
            public List<PropertyDefinition>? PropertyDefinitions { get; set; }

            private sealed class EmptyCollectionDefinition : CollectionDefinition
            {
                public EmptyCollectionDefinition()
                {
                    TypeDefinition = new TypeDefinition
                    {
                        Name = string.Empty,
                        Collection = string.Empty,
                        Namespace = string.Empty,
                        CanCreate = false,
                        CanDelete = false,
                        CanModify = false,
                        AutoGenerated = false,
                        RequiresDriver = false,
                        AccessControlled = false,
                        ChildCollections = new List<string>()
                    };
                    PropertyDefinitions = new List<PropertyDefinition>();
                }
            }
        }

        /// <summary>
        /// Represents a channel in the API documentation.
        /// </summary>
        [Endpoint("/config/v1/doc/drivers/{driverName}/channels/")]
        public class Channel : CollectionDefinition { }

        /// <summary>
        /// Represents a device in the API documentation.
        /// </summary>
        [Endpoint("/config/v1/doc/drivers/{driverName}/devices/")]
        public class Device : CollectionDefinition { }

        /// <summary>
        /// Represents a type definition in the API documentation.
        /// </summary>
        public class TypeDefinition
        {
            /// <summary>
            /// Gets or sets the name of the type.
            /// </summary>
            [JsonPropertyName("name")]
            public string? Name { get; set; }

            /// <summary>
            /// Gets or sets the collection of the type.
            /// </summary>
            [JsonPropertyName("collection")]
            public string? Collection { get; set; }

            /// <summary>
            /// Gets or sets the namespace of the type.
            /// </summary>
            [JsonPropertyName("namespace")]
            public string? Namespace { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the type can be created.
            /// </summary>
            [JsonPropertyName("can_create")]
            public bool CanCreate { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the type can be deleted.
            /// </summary>
            [JsonPropertyName("can_delete")]
            public bool CanDelete { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the type can be modified.
            /// </summary>
            [JsonPropertyName("can_modify")]
            public bool CanModify { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the type is auto-generated.
            /// </summary>
            [JsonPropertyName("auto_generated")]
            public bool AutoGenerated { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the type requires a driver.
            /// </summary>
            [JsonPropertyName("requires_driver")]
            public bool RequiresDriver { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the type is access controlled.
            /// </summary>
            [JsonPropertyName("access_controlled")]
            public bool AccessControlled { get; set; }

            /// <summary>
            /// Gets or sets the child collections of the type.
            /// </summary>
            [JsonPropertyName("child_collections")]
            public List<string>? ChildCollections { get; set; }
        }

        /// <summary>
        /// Represents a property definition in the API documentation.
        /// </summary>
        public class PropertyDefinition
        {
            /// <summary>
            /// Gets or sets the symbolic name of the property.
            /// </summary>
            [JsonPropertyName("symbolic_name")]
            public string? SymbolicName { get; set; }

            /// <summary>
            /// Gets or sets the display name of the property.
            /// </summary>
            [JsonPropertyName("display_name")]
            public string? DisplayName { get; set; }

            /// <summary>
            /// Gets or sets the display description of the property.
            /// </summary>
            [JsonPropertyName("display_description")]
            public string? DisplayDescription { get; set; }

            /// <summary>
            /// Gets or sets the group name of the property.
            /// </summary>
            [JsonPropertyName("group_name")]
            public string? GroupName { get; set; }

            /// <summary>
            /// Gets or sets the section name of the property.
            /// </summary>
            [JsonPropertyName("section_name")]
            public string? SectionName { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the property is read-only.
            /// </summary>
            [JsonPropertyName("read_only")]
            public bool ReadOnly { get; set; }

            /// <summary>
            /// Gets or sets the type of the property.
            /// </summary>
            [JsonPropertyName("type")]
            public string? Type { get; set; }

            /// <summary>
            /// Gets or sets the default value of the property.
            /// </summary>
            [JsonPropertyName("default_value")]
            public object? DefaultValue { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the property is required.
            /// </summary>
            [JsonPropertyName("required")]
            public bool Required { get; set; }

            /// <summary>
            /// Gets or sets a value indicating whether the property is server-only.
            /// </summary>
            [JsonPropertyName("server_only")]
            public bool ServerOnly { get; set; }

            /// <summary>
            /// Gets or sets the minimum length of the property.
            /// </summary>
            [JsonPropertyName("minimum_length")]
            public int MinimumLength { get; set; }

            /// <summary>
            /// Gets or sets the maximum length of the property.
            /// </summary>
            [JsonPropertyName("maximum_length")]
            public int MaximumLength { get; set; }

            /// <summary>
            /// Gets the default value as a JsonElement.
            /// </summary>
            /// <returns>The default value as a JsonElement.</returns>
            public JsonElement GetDefaultValue()
            {
                if (Type == null)
                    return KepJsonContext.WrapInJsonElement(null);

                if (DefaultValue == null)
                    return KepJsonContext.WrapInJsonElement(null);

                if (DefaultValue is JsonElement jsonElement)
                {
                    // Überprüfen, ob ValueKind mit Type übereinstimmt, ansonsten konvertieren oder Standardwert zurückgeben
                    switch (Type.ToLower())
                    {
                        case "allowdeny":
                        case "enabledisable":
                        case "yesno":
                            if (jsonElement.ValueKind == JsonValueKind.True || jsonElement.ValueKind == JsonValueKind.False)
                                return jsonElement;
                            return KepJsonContext.WrapInJsonElement(false);

                        case "string":
                        case "password":
                        case "localfilespec":
                        case "uncfilespec":
                        case "localpathspec":
                        case "uncpathspec":
                        case "stringwithbrowser":
                            if (jsonElement.ValueKind == JsonValueKind.String)
                                return jsonElement;
                            return KepJsonContext.WrapInJsonElement(string.Empty);

                        case "stringarray":
                        case "blob":
                            if (jsonElement.ValueKind == JsonValueKind.Array)
                                return jsonElement;
                            return KepJsonContext.WrapInJsonElement(new string[0]);

                        case "integer":
                        case "hex":
                        case "octal":
                        case "signedinteger":
                        case "timeofday":
                        case "date":
                        case "dateandtime":
                            if (jsonElement.ValueKind == JsonValueKind.Number && jsonElement.TryGetInt32(out int _))
                                return jsonElement;
                            return KepJsonContext.WrapInJsonElement(0);

                        case "real4":
                            if (jsonElement.ValueKind == JsonValueKind.Number && jsonElement.TryGetSingle(out float _))
                                return jsonElement;
                            return KepJsonContext.WrapInJsonElement(0.0f);

                        case "real8":
                            if (jsonElement.ValueKind == JsonValueKind.Number && jsonElement.TryGetDouble(out double _))
                                return jsonElement;
                            return KepJsonContext.WrapInJsonElement(0.0);

                        case "enumeration":
                            if (jsonElement.ValueKind == JsonValueKind.Number)
                                return jsonElement;
                            return KepJsonContext.WrapInJsonElement(0);

                        case "proparray":
                            if (jsonElement.ValueKind == JsonValueKind.Object)
                                return jsonElement;
                            return KepJsonContext.WrapInJsonElement(new object[0]);

                        default:
                            return KepJsonContext.WrapInJsonElement(null);
                    }
                }
                else
                {
                    switch (Type.ToLower())
                    {
                        case "allowdeny":
                        case "enabledisable":
                        case "yesno":
                            return KepJsonContext.WrapInJsonElement(Convert.ToBoolean(DefaultValue ?? false));
                        case "string":
                        case "password":
                        case "localfilespec":
                        case "uncfilespec":
                        case "localpathspec":
                        case "uncpathspec":
                        case "stringwithbrowser":
                            return KepJsonContext.WrapInJsonElement(DefaultValue?.ToString() ?? string.Empty);
                        case "stringarray":
                        case "blob":
                            return KepJsonContext.WrapInJsonElement(DefaultValue ?? new string[0]);
                        case "integer":
                        case "hex":
                        case "octal":
                        case "signedinteger":
                        case "timeofday":
                        case "date":
                        case "dateandtime":
                            return KepJsonContext.WrapInJsonElement(Convert.ToInt32(DefaultValue ?? 0));
                        case "real4":
                            return KepJsonContext.WrapInJsonElement(Convert.ToSingle(DefaultValue ?? 0.0f));
                        case "real8":
                            return KepJsonContext.WrapInJsonElement(Convert.ToDouble(DefaultValue ?? 0.0));
                        case "enumeration":
                            return KepJsonContext.WrapInJsonElement(DefaultValue ?? 0);
                        case "proparray":
                            return KepJsonContext.WrapInJsonElement(DefaultValue ?? new object[0]);
                        default:
                            return KepJsonContext.WrapInJsonElement(null);
                    }
                }
            }
        }
    }

    [JsonSerializable(typeof(List<Docs.Driver>))]
    [JsonSerializable(typeof(List<Docs.Channel>))]
    [JsonSerializable(typeof(List<Docs.Device>))]
    [JsonSourceGenerationOptions(WriteIndented = true)]
    internal partial class KepDocsJsonContext : JsonSerializerContext
    {
    }
}
